name: C

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'example/**'
      - 'src/**'
      - 'node/**'
      - 'CMakeLists.txt'
      - '.github/workflows/c.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'example/**'
      - 'src/**'
      - 'node/**'
      - 'CMakeLists.txt'
      - '.github/workflows/c.yml'

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            pv-platform: linux
            output-dir: linux/x86_64
          - os: windows-latest
            pv-platform: windows
            output-dir: windows/amd64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build -S . -DPV_PLATFORM="${{ matrix.pv-platform }}" -DOUTPUT_DIR="${{ matrix.output-dir }}"

    - name: Build
      run: cmake --build ./build

    - name: Run get audio devices
      run: ./demo --show_audio_devices
      working-directory: build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pv-platform }}
        path: |
          lib/${{matrix.output-dir}}/libpv_recorder.*
          lib/node/${{matrix.output-dir}}/pv_recorder.node
        retention-days: 3

  build-self-hosted-macos:
    runs-on: pv-ios

    strategy:
      matrix:
        pv-platform: [mac-arm64, mac-x86_64]
        include:
          - pv-platform: mac-arm64
            output-dir: mac/arm64
          - pv-platform: mac-x86_64
            output-dir: mac/x86_64

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build -S . -DPV_PLATFORM="${{ matrix.pv-platform }}" -DOUTPUT_DIR="${{ matrix.output-dir }}"

    - name: Build
      run: cmake --build ./build

    - name: Run get audio devices
      run: ./demo --show_audio_devices
      working-directory: build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pv-platform }}
        path: |
          lib/${{matrix.output-dir}}/libpv_recorder.*
          lib/node/${{matrix.output-dir}}/pv_recorder.node
        retention-days: 3

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
          - machine: rpi2
            pv-platform: raspberry-pi2
            output-dir: raspberry-pi/cortex-a7
          - machine: rpi3-32
            pv-platform: raspberry-pi
            output-dir: raspberry-pi/arm11
          - machine: rpi3-32
            pv-platform: raspberry-pi3
            output-dir: raspberry-pi/cortex-a53
          - machine: rpi3-64
            pv-platform: raspberry-pi3-64
            output-dir: raspberry-pi/cortex-a53-aarch64
          - machine: rpi4-32
            pv-platform: raspberry-pi4
            output-dir: raspberry-pi/cortex-a72
          - machine: rpi4-64
            pv-platform: raspberry-pi4-64
            output-dir: raspberry-pi/cortex-a72-aarch64
          - machine: jetson
            pv-platform: jetson-nano
            output-dir: jetson/cortex-a57-aarch64
          - machine: beaglebone
            pv-platform: beaglebone
            output-dir: beaglebone

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build -S . -DPV_PLATFORM="${{ matrix.pv-platform }}" -DOUTPUT_DIR="${{ matrix.output-dir }}"

    - name: Build
      run: cmake --build ./build

    - name: Run get audio devices
      run: ./demo --show_audio_devices
      working-directory: build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pv-platform }}
        path: |
          lib/${{matrix.output-dir}}/libpv_recorder.*
          lib/node/${{matrix.output-dir}}/pv_recorder.node
        retention-days: 3

  collect-artifacts:
    runs-on: ubuntu-latest
    needs: [build-github-hosted, build-self-hosted]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Make collection directory
        run: mkdir -p all-libs/lib

      - name: Collect artifacts
        shell: bash
        run: |
          for DIR in artifacts/*; do cp -a $DIR/* all-libs/lib/; done

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-libs
          path: all-libs
          retention-days: 3