name: .NET Demo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demo.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
      - '.github/workflows/dotnet-demo.yml'

defaults:
  run:
    working-directory: demo/dotnet/PvRecorderDemo

jobs:
  dotnet-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build .NET demo
      run: dotnet pack -c Release
      working-directory: binding/dotnet/PvRecorder

    - name: Restore local package
      run: dotnet add package PvRecorder -s ../../binding/dotnet/PvRecorder

    - name: Build .NET demo
      run: dotnet build

    - name: Run .NET demo
      run: dotnet run -- --show_audio_devices
